const logger = require('../logger')
const prepareData = require('../steps/prepare-data')
const lookupDsf = require('../steps/lookup-dsf')
const lookupP360 = require('../steps/lookup-p360')
const lookupKor = require('../steps/lookup-kor')
const getElevmappe = require('../steps/get-elevmappe')
const checkRestrictedAddress = require('../steps/check-restricted-address')
const setupParts = require('../steps/setup-parts')
const prepareDocument = require('../steps/prepare-document')
const setupAgreement = require('../steps/setup-agreement')
const dropDistributionCheck = require('../steps/drop-distribution-check')
const setupRestricted = require('../steps/setup-restricted')
const setupMissingGuardian = require('../steps/setup-missing-guardian')
const setupArchive = require('../steps/setup-archive')
const saveToDone = require('../steps/save-to-done')
const saveToArchive = require('../steps/save-to-archive')
const saveToDistribution = require('../steps/save-to-distribution')
const saveToErrors = require('../steps/save-to-errors')
const removeFromQueue = require('../steps/remove-from-queue')

module.exports = data => {
  logger('info', ['flows', 'laeremidler'])
  return new Promise(async (resolve, reject) => {
    prepareData(data)
      .then(lookupDsf)
      .then(prepareDocument)
      .then(lookupP360)
      .then(getElevmappe)
      .then(checkRestrictedAddress)
      .then(setupParts)
      .then(lookupKor)
      .then(dropDistributionCheck)
      .then(setupAgreement)
      .then(setupRestricted)
      .then(setupMissingGuardian)
      .then(setupArchive)
      .then(saveToDone)
      .then(saveToArchive)
      .then(saveToDistribution)
      .then(saveToErrors)
      .then(removeFromQueue)
      .then(data => resolve(data))
      .catch(error => reject(error))
  })
}
